---
# output:
#  word_document:
#     reference_docx: Extras/manuscript_template.docx
#     pandoc_args:
#       - --lua-filter=Extras/pagebreak.lua
# always_allow_html: true
hero-title: Test
hero-subtitle: test
output: myrmdtemplate::bloomberg
# bibliography: references.bib
# csl: Extras/anesthesiology.csl
link-citations: yes
params:
  pandoc: FALSE
  html: TRUE
---

# OVERALL AIM AND IMPACT OF THE RESEARCH

*The duration of fasting before medical procedures frequently far exceeds the recommended 6 hours since the last meal and 2 hours since last clear fluids. This results in unnecessary discomfort and distress for patients about to undergo an already physically and emotionally demanding experience.*

We propose that a *technological solution* is needed to properly address this problem and improve the patient experience for the large number of people undergoing medical and surgical procedures with sedation or anesthesia. This grant will enable us to develop a system to automate pre-procedural fasting instructions. First, we will create a large database containing 2 years of scheduling data for procedures performed in the cardiac catheterization laboratory at the Peter Munk Cardiac Centre, Toronto General Hospital. We will use this data to develop and validate a statistical model to predict the time 2 and 6 hours prior to actual procedure start time using state-of-the-art machine learning methods. It is proposed that these predictions could then be 'operationalized' in a real-time, automated pre-procedural fasting instruction system by triggering two separate alerts sent directly to a patient. The first alert will be when it is predicted that the procedure will commence in the next 6 hours, informing the patient to stop eating. The next alert will be sent when it is predicted that the procedure will commence within the next 2 hours, informing the patient to stop drinking clear fluids. The second core component of this program of research is to draw upon user-centered design principles in development of the automated fasting instruction system's user-facing components (i.e. the alerts that patients receive). This approach will ensure the alert system is optimally suited to patient and healthcare team requirements for providing the automated pre-procedural fasting instructions. Long-term, it is planned to evaluate the effectiveness of this automated system in a randomized controlled trial prior to broader implementation.

# OBJECTIVES